= Proxmox cloud-init VM

:toc: auto
:hardbreaks-option:

== Description

This module creates a https://www.proxmox.com/de/proxmox-ve[Proxmox VE] virtual machine, that can be configured on boot with https://cloud-init.io/[cloud-init]. To configure the VM on boot via cloud-init, you have to pass a user-data and network-data file.
Both files can be https://developer.hashicorp.com/terraform/language/functions/templatefile[terraform template files].

== Setup

=== What the module affects

* Creates a virtual machine in your Proxmox VE cluster
* Creates a snippet in your Proxmox VE cluster
* Creates a MAC address as terraform resource

=== Setup Requirements

* Working Proxmox VE host or cluster
* VM Template with cloud-init installed and enabled
* Following terraform providers:
** https://registry.terraform.io/providers/Telmate/proxmox/latest[telmate/proxmox]
** https://registry.terraform.io/providers/bpg/proxmox/latest[bpg/proxmox]
** https://registry.terraform.io/providers/ivoronin/macaddress/latest[ivoronin/macaddress]

Install and configured these providers as documented at their corresponding terraform registry entries.

=== Beginning with this module

This module uses to providers vor _Proxmox VE_ and both providers relate to the name _proxmox_, therefore they have to be named explicitly. https://github.com/yuqo2450/tf_pmx_vm_base/blob/main/example/main.tf[This example] demonstrates how to set them up. Moreover you have to pass the explicit provider name to each module with the `providers` attribute.
A basic example to use this module can be found in the https://github.com/yuqo2450/tf_pmx_vm_base/blob/main/example/main.tf[example main]. This example requires static userdata and netdata templates.

== Usage

A basic example how to use this module can be found in the https://github.com/yuqo2450/tf_pmx_vm_base/blob/main/example/main.tf[examples].

The module is designed for cloud-init support. Therefore it can *only be used* with a https://github.com/yuqo2450/tf_pmx_vm_base/blob/main/example/main.tf[`user_data`] and https://github.com/yuqo2450/tf_pmx_vm_base/blob/main/example/main.tf[`net_data`] configuration.
It is possible to use _https://developer.hashicorp.com/terraform/language/expressions/strings#string-templates[string templates]_ as `user_data` and `net_data` to configure _cloud-init_. To pass variables to the templates use the `userdata_vars` and `netdata_vars` attributes of this module:
[source, terraform]
----
userdata_vars = {
  key = "value"
}

netdata_vars  = {
  key = "value"
}
----

If the added network interfaces are supposed to have static IP addresses, add the address to the interfaces map:
[source, terraform]
----
interfaces = {
  eth0 = {
    net_bridge  = "vmbr0"
    net_vlan    = "0"
    ip4_address = "192.168.0.10/24"
  }
}
----
To use the key in a cloud-init `user_data` or `net_data` terraform template you can refer to _interfaces.eth0.ip4_address_ in the template to use the IP set for the interfaces.

== Limitations

* This module is totally based around cloud-init so you have to provide user-data and net-data files
* Without a cloud-init image it is not possible to configure the operating system of the VMs
